name: python pp
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: latest

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/<service-id>/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
